import re
from pathlib import Path

file_path = Path('api/report_generator.py')
if not file_path.exists():
    print("❌ File tidak ditemukan di api/report_generator.py")
    exit(1)

with open(file_path, 'r') as f:
    content = f.read()

# Definisikan fungsi generate_esg_pdf yang sehat dan rapi
fixed_function = """def generate_esg_pdf(report_data):
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("helvetica", "B", 18)
    pdf.cell(0, 12, "GeoESG A.E.C.O Audit Report", new_x="LMARGIN", new_y="NEXT", align="C")
    pdf.set_font("helvetica", "", 10)
    pdf.cell(0, 8, f"Generated: {report_data.get('timestamp', '')}", new_x="LMARGIN", new_y="NEXT", align="C")
    pdf.ln(5)
    pdf.set_font("helvetica", "B", 14)
    pdf.cell(0, 10, "Area of Interest (AOI)", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("helvetica", "", 11)
    pdf.cell(0, 8, f"Geometry Type: {report_data.get('geometry_type', 'N/A')}", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 8, f"Raster CRS: EPSG:{report_data.get('raster_crs', 'N/A')}", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 8, f"Pixel Resolution: {report_data.get('pixel_resolution_m', 'N/A')} m", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(5)
    pdf.set_font("helvetica", "B", 14)
    pdf.cell(0, 10, "Flood Statistics (AOI-Clipped)", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("helvetica", "", 12)
    stats = [
        ("Total AOI Area", f"{report_data.get('total_area_ha', 0)} Ha"),
        ("Flooded AOI Area", f"{report_data.get('flooded_area_ha', 0)} Ha"),
        ("Flood Percentage", f"{report_data.get('flood_percentage', 0)}%"),
        ("Total Pixels (Valid)", str(report_data.get("total_pixels", 0))),
        ("Flooded Pixels", str(report_data.get("flooded_pixels", 0))),
    ]
    for label, value in stats:
        pdf.cell(0, 9, f"{label}: {value}", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(8)
    pdf.set_font("helvetica", "B", 14)
    pdf.cell(0, 10, "Methodology", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("helvetica", "", 10)
    method_text = ("Flood detection via multisensor fusion: Sentinel-1 SAR backscatter thresholding "
                   "combined with Sentinel-2 NDWI verification. Spatially clipped to AOI.")
    pdf.multi_cell(0, 6, method_text)
    pdf.ln(5)
    pdf.set_font("helvetica", "I", 8)
    disclaimer = ("This report is auto-generated by the GeoESG A.E.C.O pipeline. "
                  "Statistics are computed per-pixel and may differ from vector-based area calculations.")
    pdf.multi_cell(180, 5, disclaimer, align="L")
    out_dir = Path("/tmp/reports")
    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / f"esg_report_{uuid.uuid4().hex[:8]}.pdf"
    pdf.output(str(out_path))
    return str(out_path)"""

# Gunakan regex untuk mengganti fungsi yang rusak dari 'def generate_esg_pdf' sampai akhir
pattern = r'def generate_esg_pdf\(.*?\):\n.*?(?=\n\n|\Z)'
new_content = re.sub(pattern, fixed_function, content, flags=re.DOTALL)

with open(file_path, 'w') as f:
    f.write(new_content)
print("✅ Sintaks report_generator.py berhasil diperbaiki!")
