import re

file_path = 'api/report_generator.py'
with open(file_path, 'r') as f:
    content = f.read()

# Pola untuk mencari blok teks yang offside
old_pattern = r'pdf\.cell\(\s*0,\s*5,\s*"This report is auto-generated.*?",\s*new_x="LMARGIN",\s*new_y="NEXT",\s*\)'

# Pengganti dengan multi_cell dan font miring (Italic)
new_logic = """pdf.ln(5)
    pdf.set_font("helvetica", "I", 8)
    pdf.multi_cell(
        0, 5,
        "This report is auto-generated by the GeoESG A.E.C.O pipeline. "
        "Statistics are computed per-pixel and may differ from vector-based area calculations."
    )"""

if "multi_cell" not in content:
    new_content = re.sub(old_pattern, new_logic, content, flags=re.DOTALL)
    with open(file_path, 'w') as f:
        f.write(new_content)
    print("✅ File report_generator.py BERHASIL diperbaiki di VPS!")
else:
    print("ℹ️ File sepertinya sudah menggunakan multi_cell.")
