import re

file_path = 'api/report_generator.py'
with open(file_path, 'r') as f:
    content = f.read()

# Kita cari blok footer yang bandel itu
# Pola ini lebih fleksibel terhadap spasi/indentasi
footer_pattern = r'pdf\.set_font\("helvetica", "I", 8\)\s+pdf\.cell\(\s*0,\s*5,\s*"This report is auto-generated.*?\n\s*\)'

# Kita ganti paksa ke multi_cell
new_footer = """pdf.set_font("helvetica", "I", 8)
    pdf.multi_cell(
        190, 5,
        "This report is auto-generated by the GeoESG A.E.C.O pipeline. "
        "Statistics are computed per-pixel and may differ from vector-based area calculations.",
        align="L"
    )
"""

# Cari teks lama dan ganti
updated_content = re.sub(
    r'pdf\.set_font\("helvetica", "I", 8\)\s+pdf\.multi_cell\(.*?area calculations\."\s*\)', 
    new_footer, 
    content, 
    flags=re.DOTALL
)

# Jika cara di atas gagal, kita pakai cara yang paling brutal: cari string uniknya
if "area calculations" in updated_content:
    print("Sedang memproses penggantian teks footer...")
    # Update manual bagian footer
    with open(file_path, 'w') as f:
        f.write(updated_content)
    print("✅ Footer BERHASIL dipaksa masuk margin!")
else:
    print("❌ Teks tidak ditemukan, pastikan path file benar.")
