
file_path = 'api/report_generator.py'
with open(file_path, 'r') as f:
    lines = f.readlines()

new_lines = []
skip = False
for line in lines:
    # Cari awal blok disclaimer
    if 'This report is auto-generated' in line:
        # Masukkan versi multi_cell yang miring dan aman margin
        new_lines.append('    pdf.ln(5)\n')
        new_lines.append('    pdf.set_font("helvetica", "I", 8)\n')
        new_lines.append('    pdf.multi_cell(180, 5, "This report is auto-generated by the GeoESG A.E.C.O pipeline. Statistics are computed per-pixel and may differ from vector-based area calculations.", align="L")\n')
        skip = True # Lewati baris-baris lama yang mungkin masih format .cell()
        continue
    
    if skip and ')' in line: # Berhenti skip setelah ketemu tutup kurung fungsi lama
        skip = False
        continue
        
    if not skip:
        new_lines.append(line)

with open(file_path, 'w') as f:
    f.writelines(new_lines)
print("🚀 LOGIKA PDF TELAH DI-RESET TOTAL KE MULTI_CELL!")
